name: cmLoja
version: 1.6-SNAPSHOT
main: gmail.fopypvp174.cmloja.CmLoja
authors: [C4ssi0]
description: Plugin de loja
depend: [Vault]
commands:
  geraritem:
    description: Gerar um item customizado para loja
    usage:
    permission: loja.geraritem
    permission-message: "§cVocê não tem permissão para usar o comando '/geraritem'."
    aliases: [itemgerar]

permissions:
  loja.geraritem:
    description: Permissão para o jogador poder gerar um item customizado na loja.
    default: op
